# Generated by Django 6.0.1 on 2026-02-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='photo',
            field=models.FileField(blank=True, upload_to='skill_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.FileField(upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
