# Generated by Django 6.0.1 on 2026-02-10 07:07

import portfolio_api.image_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0003_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=portfolio_api.image_utils.CompressedImageField(upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='photo',
            field=portfolio_api.image_utils.CompressedImageField(blank=True, upload_to='skill_photos/'),
        ),
    ]
