# Generated by Django 6.0.1 on 2026-02-10 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0004_alter_profile_avatar_url_alter_skillcategory_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_size', models.PositiveIntegerField(help_text='Original file size in bytes')),
                ('path_original', models.CharField(max_length=500)),
                ('path_icon', models.CharField(max_length=500)),
                ('path_normal', models.CharField(max_length=500)),
                ('path_large', models.CharField(max_length=500)),
                ('content_field', models.CharField(help_text='app_label.Model.field that owns this file', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
